#! /bin/sh

### BEGIN INIT INFO
# Provides:          logstash-shipper
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

. /lib/lsb/init-functions

mode="indexer"
name="logstash-$mode"
logstash_bin="/usr/bin/java -- -Xmx512M -Xms256M -Djava.net.preferIPv4Stack=true -jar /opt/logstash/logstash.jar"
logstash_conf="/etc/logstash/conf.d/"
logstash_grok_path="/etc/logstash/grok/"
logstash_log="/var/log/logstash/$name.log"
pid_file="/var/run/logstash/$name.pid"
runas="logstash:logstash"

NICE_LEVEL="-n 10"

start () {
    command="/usr/bin/nice ${NICE_LEVEL} ${logstash_bin} agent -f ${logstash_conf} --grok-patterns-path ${logstash_grok_path} --log ${logstash_log}"

    log_daemon_msg "Starting $mode" "$name"
    ulimit -n 8096
    if start-stop-daemon --start -c $runas --quiet --oknodo --pidfile "$pid_file" -b -m --exec $command; then
        log_end_msg 0
    else
        log_end_msg 1
    fi
}

stop () {
    start-stop-daemon --stop --quiet --oknodo --pidfile "$pid_file"
}

status () {
    status_of_proc -p $pid_file "" "$name"
}

case $1 in
    start)
        if status; then exit 0; fi
        start
        ;;
    stop)
        stop
        ;;
    reload)
        stop
        start
        ;;
    restart)
        stop
        start
        ;;
    status)
        status && exit 0 || exit $?
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload|status}"
        exit 1
        ;;
esac

exit 0
